/*
 * Copyright 2011 Chase Barrett. All rights reserved.
 * PROPRIETARY/CONFIDENTIAL. 
 */
package com.spi.sierra;

import java.io.BufferedInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Stack;
import java.util.TreeMap;

import javax.swing.text.MutableAttributeSet;
import javax.swing.text.html.HTML.Attribute;
import javax.swing.text.html.HTML.Tag;
import javax.swing.text.html.HTMLEditorKit;
import javax.swing.text.html.parser.ParserDelegator;

import org.w3c.dom.Document;
import org.w3c.dom.NamedNodeMap;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

import com.spi.AbstractInputProvider;
import com.spi.Order;
import com.spi.util.Debug;

/**
 * @author Chase Barrett
 */
public class SierraAccess extends AbstractInputProvider
{
   private static final String DEBUG_PREFIX = "SierraAccess.";
   private static List<OutputField> cFields;
   private static final long THREE_MONTHS = 3l * 30l * 24l * 60l * 60l * 1000l;
   private static final long TWO_YEARS = 8 * THREE_MONTHS; 
   private static final SimpleDateFormat SHORT_FORMAT = new SimpleDateFormat("MM/dd/yyyy");
   
   private Web mWeb;

   public String getServiceCompany()
   {
      return "Sierra Field Services";
   }

   public List<Order> getAllOrders()
   {
      if (Debug.checkLevel(Debug.MED)) Debug.debug(Debug.MED, DEBUG_PREFIX + "getAllOrders(): START");

      // Set up the list of orders
      List<SierraOrder> orders = new ArrayList<SierraOrder>();
      try
      {
         // Set up our search by posting search criteria
         Map<String, String> params = getSearchParams();
         params.put("TextBoxCreatedStart", SHORT_FORMAT.format(new Date(System.currentTimeMillis() - THREE_MONTHS)));
         InputStream dontCare = getWeb().getInput("http://ezinspections.com/inspManager/searchJobs.aspx", params);
         dontCare.close();
         
         // Go get the pages searched for
         processPage(getWeb().getInput(getWeb().getInputURL()), orders);
      }
      catch (IOException e)
      {
         getStatistics().setErrorOccurred();
         Debug.debugException("Ooops!", e);
      }
      
      if (Debug.checkLevel(Debug.MED)) Debug.debug(Debug.MED, DEBUG_PREFIX + "getAllOrders(): Total number of orders available: " + orders.size());

      for (SierraOrder order : orders)
      {
         try
         {
            processOrder(order);
         }
         catch (Exception e)
         {
            Debug.debugException("Unable to retrieve details for order: " + order.getTrackingNo(), e);
         }
      }

      getStatistics().setNumIOsTotal(orders.size());
      if (Debug.checkLevel(Debug.MED)) Debug.debug(Debug.MED, DEBUG_PREFIX + "getAllOrders(): END: " + orders.size());
      return new ArrayList<Order>(orders);
   }

   public List<OutputField> getSupportedFields()
   {
      if (cFields == null)
      {
         cFields = new ArrayList<OutputField>(20);
         cFields.add(OutputField.PROP_NO);
         cFields.add(OutputField.PROPERTY_ADDRESS);
         cFields.add(OutputField.CITY);
         cFields.add(OutputField.ST);
         cFields.add(OutputField.ZIP_CODE);
         cFields.add(OutputField.MORTGAGER);
         cFields.add(OutputField.LOAN_NO);
         cFields.add(OutputField.MTG_COMP);
         cFields.add(OutputField.REP);
         cFields.add(OutputField.WAGES);
         cFields.add(OutputField.COST);
         cFields.add(OutputField.REPORT_TYPE);
         cFields.add(OutputField.RECD_IN);
         cFields.add(OutputField.REP_COMP_DATE);
         cFields.add(OutputField.DUE_SERV);
         cFields.add(OutputField.IS_RURAL);
         cFields.add(OutputField.PHOTOS_Y_N);
         cFields.add(OutputField.FOR_SALE);
         cFields.add(OutputField.FOR_SALE_PHONE);
         cFields.add(OutputField.OCCUPANCY);
         cFields.add(OutputField.PERSONAL_CONTACT);
         cFields.add(OutputField.PROPERTY_DESCRIPTION);
         cFields.add(OutputField.VALUE);
         cFields.add(OutputField.COMMENTS);
      }
      return cFields;
   }
   
   protected Web getWeb()
   {
      if (mWeb == null)
      {
         mWeb = new Web(getEnvironment(), getName());
      }
      return mWeb;
   }
   
   protected void processPage(InputStream is, List<SierraOrder> orders)
   {
      try
      {
         // Set up the input stream
         BufferedInputStream buf = new BufferedInputStream(is);

         // Set up the document
         Document doc = getWeb().parseInput(buf);

         // Find orders in the content table on the current page
         NodeList tables = doc.getElementsByTagName("table");
         for (int i = 0; i < tables.getLength(); i++)
         {
            Node table = tables.item(i);
            Node idAttr = table.getAttributes().getNamedItem("id");
            if (idAttr != null && "_ctl0_Main_JobGridView".equals(idAttr.getNodeValue()))
            {
               orders.addAll(processTable(table));
            }
         }
         
         // See if there is a continuation page
         NodeList anchors = doc.getElementsByTagName("a");
         boolean hasNextPage = false;
         for (int i = 0; i < anchors.getLength(); i++)
         {
            Node anchor = anchors.item(i);
            Node idAttr = anchor.getAttributes().getNamedItem("id");
            if (idAttr != null && "_ctl0_Main_PageNavigatorTop_ButtonPageNext".equals(idAttr.getNodeValue()))
            {
               hasNextPage = true;
            }
         }
         
         if (hasNextPage)
         {
            // Find all the hidden form variables and go to continuation page
            NodeList inputs = doc.getElementsByTagName("input");
            Map<String, String> params = new TreeMap<String, String>();
            for (int i = 0; i < inputs.getLength(); i++)
            {
               Node input = inputs.item(i);
               NamedNodeMap attrs = input.getAttributes(); 
               Node typeAttr = (attrs == null) ? null : attrs.getNamedItem("type");
               if (typeAttr != null && "hidden".equals(typeAttr.getNodeValue()))
               {
                  Node nameAttr = attrs.getNamedItem("name");
                  Node valueAttr = attrs.getNamedItem("value");
                  if (nameAttr != null) 
                  {
                     params.put(nameAttr.getNodeValue(), valueAttr == null ? "" : valueAttr.getNodeValue());
                  }
               }
            }
            
            // Goto the next page 
            params.put("__EVENTTARGET", "_ctl0:Main:PageNavigatorTop:ButtonPageNext");
            params.put("__EVENTARGUMENT", "");
            params.put("__LASTFOCUS", "");
            processPage(getWeb().getInput(getWeb().getInputURL(), params), orders);
         }
      }
      catch (Exception e)
      {
         getStatistics().setErrorOccurred();
         Debug.debugException("Ooops!", e);
      }
   }

   protected List<SierraOrder> processTable(Node table)
   {
      List<SierraOrder> orders = new ArrayList<SierraOrder>();

      NodeList rows = table.getChildNodes();

      for (int i = 1 /* skip the header row */; i < rows.getLength(); i++)
      {
         Node row = rows.item(i);
         NodeList cells = row.getChildNodes();

         String sysIdStr = cells.item(0).getChildNodes().item(2).getAttributes().getNamedItem("value").getNodeValue();
         String orderNumStr = cells.item(4).getFirstChild().getFirstChild().getNodeValue();

         SierraOrder order = new SierraOrder(this, orderNumStr);
         order.setSysId(sysIdStr);
         orders.add(order);
      }

      if (Debug.checkLevel(Debug.HIGH)) Debug.debug(Debug.HIGH, DEBUG_PREFIX + "processTable(): " + rows.getLength() + " rows in the table.");

      return orders;
   }
   
   protected void processOrder(SierraOrder order) throws IOException
   {
      InputStream input = getWeb().getInput(order.getDetailsLink());
      Reader reader = new InputStreamReader(input);
      ValueScraper scraper = new ValueScraper();
      new ParserDelegator().parse(reader, scraper, false);
      Map<String, String> values = scraper.getValueMap();
      
      // Complete Date
      try
      {
         Date completeDate = getDate(values.get("t"));
         if (completeDate != null) order.setCompleteDate(completeDate);
      }
      catch (Exception e)
      {
         Debug.debugException("Unable to read the complete date for order at: " + order.getDetailsLink(), e);
      }
      
      // Rep Due Date
      try
      {
         Date dueDate = getDate(values.get("dueDate"));
         if (dueDate != null) order.setRepDueDate(dueDate);
      }
      catch (Exception e)
      {
         Debug.debugException("Unable to read the due date for order at: " + order.getDetailsLink(), e);
      }
      
      // Start Date
      try
      {
         Date startDate = getDate(values.get("WSD"));
         if (startDate != null) order.setStartDate(startDate);
      }
      catch (Exception e)
      {
         Debug.debugException("Unable to read the start date for order at: " + order.getDetailsLink(), e);
      }

      // Miscellaneous
      order.setMortgagor(values.containsKey("NAME") ? values.get("NAME") : values.get("MA"));
      order.setAddress(values.get("ADDR"));
      order.setCity(values.get("CITY"));
      order.setState(values.get("STATE"));
      order.setZip(values.get("ZIP"));
      order.setClient(values.get("CLIENT"));
      order.setAccountNumber(values.get("LONUM"));
      order.setPropertyId(values.get("PID"));
      order.setServiceType(values.get("servicecode"));
      order.setOccupancy(values.containsKey("CHOISE") ? values.get("CHOISE") : values.get("OPYSTATUS"));
      order.setOccupancyVerifiedBy(values.containsKey("DETER") ? values.get("DETER") : values.get("OPYVER"));
      order.setForSale(values.get("SALE"));
      order.setSignInYard(values.get("SIY"));
      order.setRealEstateCompany(values.get("1"));
      order.setRealtorPhoneNumber(values.get("2"));
      order.setBuildingType(values.containsKey("STRTYPE") ? values.get("STRTYPE") : values.get("BULTYPE"));
      order.setConstructionType(values.containsKey("CONSTR") ? values.get("CONSTR") : values.get("CONTYPE"));
      order.setStories(values.get("STORY"));
      order.setColor(values.get("COLOR"));
      order.setGarageType(values.containsKey("GARAGE") ? values.get("GARAGE") : values.get("3"));
      order.setPropertyCondition(values.containsKey("PC") ? values.get("PC") : values.get("PROCON"));
      order.setNeighborhoodCondition(values.containsKey("NC") ? values.get("NC") : values.get("NBORCON"));
   }

   protected Map<String, String> getSearchParams()
   {
      Map<String, String> params = new HashMap<String, String>();
      params.put("__EVENTTARGET", "");
      params.put("__EVENTARGUMENT", "");
      params.put("__LASTFOCUS", "");
      params.put("__VIEWSTATE", "/wEPDwUKMTE0NzIzMzMzMw9kFgICAg9kFjhmDw9kFgIeB29uY2xpY2sFIWphdmFzY3JpcHQ6cmV0dXJuIHZhbGlkYXRlRGF0YSgpO2QCBQ8PZBYCHgdvbmZvY3VzBSpqYXZhc2NyaXB0OiBhdXRvU2VsZWN0KCdSYWRpb0J1dHRvbkpvYklkJylkAgcPD2QWAh8BBSxqYXZhc2NyaXB0OiBhdXRvU2VsZWN0KCdSYWRpb0J1dHRvbkpvYk5hbWUnKWQCCA8QDxYCHgRUZXh0BQZKb2IgSURkZGRkAgkPD2QWAh8BBS5qYXZhc2NyaXB0OiBhdXRvU2VsZWN0KCdSYWRpb0J1dHRvblBvbGljeU51bScpZAIKDxAPFgIfAgUHQWRkcmVzc2RkZGQCCw8PZBYCHwEFKWphdmFzY3JpcHQ6IGF1dG9TZWxlY3QoJ1JhZGlvQnV0dG9uQWRkcicpZAIMDxBkEBU1A0FsbAJBSwJBTAJBUgJBWgJDQQJDTwJDVAJEQwJERQJGTAJHQQJISQJJQQJJRAJJTAJJTgJLUwJLWQJMQQJNQQJNRAJNRQJNSQJNTgJNTwJNUwJNVAJOQwJORAJORQJOSAJOSgJOTQJOVgJOWQJPSAJPSwJPUgJQQQJQUgJSSQJTQwJTRAJUTgJUWAJVVAJWQQJWVAJXQQJXSQJXVgJXWRU1AAJBSwJBTAJBUgJBWgJDQQJDTwJDVAJEQwJERQJGTAJHQQJISQJJQQJJRAJJTAJJTgJLUwJLWQJMQQJNQQJNRAJNRQJNSQJNTgJNTwJNUwJNVAJOQwJORAJORQJOSAJOSgJOTQJOVgJOWQJPSAJPSwJPUgJQQQJQUgJSSQJTQwJTRAJUTgJUWAJVVAJWQQJWVAJXQQJXSQJXVgJXWRQrAzVnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2RkAhAPEA8WAh4LXyFEYXRhQm91bmRnZBAVCQpVbmFzc2lnbmVkCEFjY2VwdGVkCFJlamVjdGVkB1BlbmRpbmcKSW5jb21wbGV0ZQhDb21wbGV0ZQhWZXJpZmllZAlTdWJtaXR0ZWQJQ2FuY2VsbGVkFQkBVQFBAVIBTgFJAUMBVgFCAVgUKwMJZ2dnZ2dnZ2dnZGQCEQ8QDxYCHgdWaXNpYmxlaGRkZGQCEg8QZA8WAQICFgEQBRNVbnVzZWQgZm9yIDIgTW9udGhzBQtFWkkyMDEwMDYzMGdkZAIkDxAPZBYCHghvbmNoYW5nZQUYamF2YXNjcmlwdDpzaG93RmFjdG9ycygpEBUgA0FsbBVCQUMgLSBMb3NzIERyYWZ0IEZvcm0YQ29yZWxvZ2ljIFJFTyBJbnNwZWN0aW9uI0ZBRlMgSW5zdXJhbmNlIEFwcG9pbnRtZW50IFRyYWNraW5nI0ZBRlMgSW5zdXJhbmNlIER3ZWxsaW5nIE9ic2VydmF0aW9uCkhVRCA5NTE2LWEbTSZNIC0gQ29tbWVyY2lhbCBJbnNwZWN0aW9uEE0mTSAtIExvc3MgRHJhZnQVTUNTIC0gTG9zcyBEcmFmdCBGb3JtHU1vcnRnYWdlIEluc3BlY3Rpb24gLSBCQUMtUFBPHU1vcnRnYWdlIEluc3BlY3Rpb24gLSBCQUMtUkVPJU1vcnRnYWdlIEluc3BlY3Rpb24gLSBCYW5rIG9mIEFtZXJpY2EaTW9ydGdhZ2UgSW5zcGVjdGlvbiAtIEZBRlMZTW9ydGdhZ2UgSW5zcGVjdGlvbiAtIElNUyRNb3J0Z2FnZSBJbnNwZWN0aW9uIC0gTFBTIChGaWRlbGl0eSkZTW9ydGdhZ2UgSW5zcGVjdGlvbiAtIE1DUxhNb3J0Z2FnZSBJbnNwZWN0aW9uIC0gTU0ZTW9ydGdhZ2UgSW5zcGVjdGlvbiAtIE1TSR1Nb3J0Z2FnZSBJbnNwZWN0aW9uIC0gTVNJIE5ldyhNb3J0Z2FnZSBJbnNwZWN0aW9uIC0gUmVsaWFuY2UgQmktV2Vla2x5J01vcnRnYWdlIEluc3BlY3Rpb24gLSBSZWxpYW5jZSBEZXRhaWxlZC1Nb3J0Z2FnZSBJbnNwZWN0aW9uIC0gUmVsaWFuY2UgRmllbGQgU2VydmljZXMZTW9ydGdhZ2UgSW5zcGVjdGlvbiAtIFNQSRBNU0kgLSBMb3NzIERyYWZ0H1Byb3BlcnR5IFByZXNlcnZhdGlvbiAtIEN5cHJleHgcUHJvcGVydHkgUHJlc2VydmF0aW9uIC0gRkFGUyZQcm9wZXJ0eSBQcmVzZXJ2YXRpb24gLSBGQUZTIEdyYXNzIEN1dBtQcm9wZXJ0eSBQcmVzZXJ2YXRpb24gLSBGQVMbUHJvcGVydHkgUHJlc2VydmF0aW9uIC0gTUNTG1Byb3BlcnR5IFByZXNlcnZhdGlvbiAtIFNQSSVQcm9wZXJ0eSBQcmVzZXJ2YXRpb24gUmVjdXJyaW5nIC0gU1BJL1Jlc2lkZW50aWFsIEluc3BlY3Rpb24gLSBJbnN1cmFuY2UgTG9zcyBDb250cm9sFSAACzI1fEJBQy1MT1NTDDI1fENMLVJFT0NISwoyNXxGQS1BUFBUCjI1fEZBLUxPU1MMMjV8SFVELTk2MTVBCTI1fE1NQ09NTQkyNXxNTUxPU1MLMjV8TUNTLUxPU1MKMjV8QkFDLVBQTwoyNXxCQUMtUkVPCjI1fENXLUlOU1AKMjV8RkEtSU5TUAsyNXxJTVMtSU5TUAYyNXxGSVMLMjV8TUNTLUlOU1AKMjV8TU0tSU5TUAsyNXxNU0ktSU5TUAwyNXxNU0ktSU5TUDIJMjV8UkZTLUJXCTI1fFJGUy1EVAsyNXxSRlMtSU5TUAYyNXxTUEkKMjV8TVNJTE9TUwoyNXxDWVBYLVBQBTI1fEZBCDI1fEZBLUdDBjI1fEZBUwYyNXxNQ1MJMjV8U1BJLVBQCjI1fFNQSVItUFAGMjV8UkVTFCsDIGdnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZGQCJQ8QD2QWAh8ABRhqYXZhc2NyaXB0OnNob3dGYWN0b3JzKClkZGQCJw8PFgQeC05hdmlnYXRlVXJsBSVqYXZhc2NyaXB0OnNob3dIZWFkZXIoJ1RhYmxlSGVhZGVyJyk7HwRoZGQCKA8PZBYCHgVzdHlsZQUNZGlzcGxheTpub25lO2QCKg8QZBAVDANBbGwDQkFDCUNvcmVsb2dpYyFJTVMvSW50ZWdyYXRlZCBNb3J0Z2FnZSBTb2x1dGlvbnMaTGVuZGVyIFByb2Nlc3NpbmcgU2VydmljZXMDTSZNFk1PUlRHLiBDT05UUi4gU0VSVklDRVMfTW9ydGdhZ2UgQ29udHJhY3RpbmcgU2VydmljZXMgMgNNU0kPTkFUJ0wgRklFTEQgUkVQF1JlbGlhbmNlIEZpZWxkIFNlcnZpY2VzGVNpZXJyYSBGaWVsZCBTZXJ2aWNlIEluYy4VDAAEMjcxMgQxNjU2BDE2MjUEMTU2MAQyNzEzBDIxMTEENDYwMwQzMDY5BDQwNTQENDcxMgQyMjc0FCsDDGdnZ2dnZ2dnZ2dnZ2RkAisPEA8WAh4EUm93cwIIZBAVsgQDQWxsBE5vbmUCTWUaQWNraWUgR2VvcmdlIC0gS1kzMDY3ICAoMCkWQWRhbSBNYW5uIC0gQ0E1NjAgICgwKRpBaW1lZSBMZWhtYW4gLSBORDYwMTQgICgwKRtBbGV4YW5kZXIgUnVpeiAtIENBNTk5ICAoMikZQWxsYW4gRXdpbmcgLSBLWTMwNjggICgwKRpBbGxlbiBTZWNrbWFuIC0gTUk4MDMgICgwKR9BbHZpbiBKYW1lcyBUaGF5ZXIgLSBDQTMxNyAgKDIpHUFtYW5kYSBLcm9nZXIgLSBUTjEwMDEgICg3MzUpE0FuZHJlYSBQaWxncmltICAoMCkcQW5kcmV3IERveWxlIC0gV0E1NDYgICg1MDk3KRpBbmRyZXcgRG95bGUgLSBXQTU0NkMgICgwKRpBbmRyZXcgRG95bGUgLSBXQTU0NkQgICgwKRpBbmRyZXcgRG95bGUgLSBXQTU0NkUgICgwKRpBbmRyZXcgRG95bGUgLSBXQTU0NkcgICgwKRtBbmdlbGEgQWx2YXJleiAtIENBNDQ5ICAoMCkZQW5nZWxhIEN1cnRpcy1LWTMwNzQgICgxKR1BbmdlbGEgSHVnaGVzIC0gS1kzMDAwICAoMjE4KRtBbmdlbGEgTGFyc29uIC0gTU45MDQxICAoMCkfQW5nZWxhIFJpbmFsZGkgLSBNTjkwMDEgICgxMjA1KR1BbmdlbGEgV2FkZGVsbCAtIFROMTAyMSAgKDYyKThBbml0YSBEYXZpcyBHZW0gU3RhdGUgSW5zcGVjdGlvbiBTZXJ2aWNlcyAtIElENTg4ICAoNTA5KTlBbml0YSBEYXZpcyBHZW0gU3RhdGUgSW5zcGVjdGlvbiBTZXJ2aWNlcyAtIElENTg4QSAgKDQ5MikcQW5uIEhhcmtuZXNzIC0gVE4xMDAyICAoODc5KRlBbm4gTWFyY2hhbmQgLSBOVjIyMSAgKDApG0FudGhvbnkgT2xzb24gLSBNTjkwNjEgICg2KRxBbnRob255IFdhbGxhY2UgLSBDQTQxNCAgKDYpHkFudG9uIFNoYXJhYmFyaW4gLSBPUjIzMSAgKDk2KRtBcHJpbCBNY0tpbnppZSAtIENBNTM4ICAoNikgQXJpYW5uYSBTZXZlcmluaSAtIENPNTAwOSAgKDE2NikfQXJpYW5uYSBTZXZlcmluaSBDTzUwMDlBICAoMjU0KRxBcmxlbmUgSGlja2VsIC0gTkQ2MDA1ICAoMTkpGkFybGVuZSBNZWx0b24gLSBOVjI2MCAgKDQpGkFzaGxleSBQZXJyeSAtIE9SMjc0ICAoMTUpG0FzaGxleSBTaG9yZSAtIE5WMjQyICAoNTg0KRxCYXJiYXJhIEthYnJpY2sgLSBXQTYwOCAgKDApHEJhcnJ5IEJvaGFubm9uIFROMTAxOSAgKDE3NikwQmFydCBEYWxtYXNzbyBBbGwgUmVhbCBFc3RhdGUsIExMQyAtIFdBNjA2ICAoMTApGUJlY2t5IEFzaGNyYWZ0IENBNTQ5ICAoMykdQmVuIFZhbiBHZXJwZW4gLSBXQTUzNCAgKDU0NCkbQmVybmljZSBQYWdlbCAtIENPNTA1MSAgKDEpGUJlcm5pY2UgU3RhY3ktS1kzMDczICAoMCkcQmVybml0YSBPd2luZ3MgLSBDTzUwNzUgICgwKRRCZXRoIFViaWwgQ0E0ODggICgwKRxCZXRoYW5uIFdpbnRlciAtIE1OOTAyMSAgKDQpHEJldHR5IEtlZmZlbGVyIC0gSUQ1MjUgICg2OCkbQmV0dHkgVGhhdGNoZXIgLSBDQTUxMSAgKDApG0JldmVybHkgTWFzdGVycy1NSTgxNCAgKDIyKRtCaWxsIEJlcnRvbGlvIC0gVVQ3MDEwICAoMCkWQmlsbCBIYXNzIC0gTUk3NTggICg4KRpCaWxsIFZpcmRlbiAtIENPNTA5NyAgKDM1KRlCaWxsIFdlcm5lciAtIENPNTAzMCAgKDQpNkJpbGwgU2NobWlldHQgTW91bnRhaW4gUmFuY2ggUmVhbHR5LCBJbmMuIC0gQ0E1ODkgICgxKRpCaWxseSBKZWZmcmV5IC0gQ0E1ODMgICgwKRhCb2IgSGVyYnN0IC0gTVQyMDIwICAoMSkWQm9iIEphcmsgLSBXQTU2NiAgKDYxKR5Cb25uaWUgV2FrZWZpZWxkIC0gV1k0MDA3ICAoMCkYQm95ZCBIYXJyaXMgLSBPUjIzNyAgKDQpH0JyYWRsZXkgQnVybWVpc2VyIE1OLTkwMjUgICg0OCkeQnJhbmR5IE1vb3JpbmcgLSBDTzUwMzcgICgxMDUpGkJyZW5kYSBadW5pZ2EgLSBDQTU1MyAgKDApG0JyaWFuIEJha2VyIC0gTUk3MzYgICgzNzc2KRpCcmlhbiBSb3RoIC0gT1IyMjggICgyMTQ5KSBCcmlhbiBFIFR1cm5xdWlzdCAtIElENTY4ICAoMjA0KRxCcm9va2UgU2ltcHNvbiBNTjkwNDggICg0NjApGkJydWNlIEdvdmFuIC0gV0E1MjYgICgxOTEpGUJydWNlIEpvbmVzIC0gTUk3OTEgICgyMykbQnJ1Y2UgUmljaG1hbiAtIE5WMjA3ICAoMzApHUJydWNlIFJpY2htYW4gLSBOVjIwN0EgICg0MzgpHEJyeWFudCBNdWxsaW5peCBUTjEwMDggICgyMykZQnVkIE5lc2xpbiAtIE9SMjA1ICAoMzA4KRhDLlIuIFByaW5jZSAtIE5WMjMwICAoMCkeQ2FtcGJlbGwgTWNDbHVza3kgLSBXQTUxOCAgKDcpGUNhcmwgQ2FybHNvbiAtIFdBNjAzICAoMSkZQ2Fyb2xlIERlTWFycyBORDYwMjEgICg4KRhDYXJvbGUgSGljZSAtIENBNDM5ICAoMykYQ2FyeSBMaWdvbiAtIFdBNDU4ICAoOTEpI0NhdGhlcmluZSBIaWxseS1SZWRnYXRlIENPNTA0NyAgKDYpE0NhdGh5IE1haGFmZmV5ICAoMCkoQ2hhZCBEaXhvbiBUZWNoIDUgUmVhbHR5IC0gTU45MDE0ICAoNzcyKRlDaGFkZCBCb3llciAtIE1OOTAzMyAgKDEpHENoYXJsZW5lIFd5bWFuIC0gSUQ1MjEgICg3MikdQ2hhcmxlcyBIYXJ0b24gLSBOVjIwOCAgKDEwNikfQ2hhcmxlcyBXIFZhdWdobiAtIE1JNzM4ICAoNTc2KSBDaGFybGVzIFcgVmF1Z2huIC0gTUk3MzhBICAoMTQwKR5DaGFybG90dGUgTWlsbGVyIC0gTVQyMDc2ICAoMSkcQ2hlcmllIE5ldWRpY2sgLSBNVDIwNzcgICgwKRpDaGVyeWwgU3RlZmZlbi1XQTYwNCAgKDEyKRpDaHJpcyBIZW1icmVlIEtZMzA1MiAgKDE3KRpDaHJpcyBNaWxsZXIgLSBXQTU5OCAgKDE3KR1DaHJpc3RhIEdhcmNpYSAtIFdBNTU2ICAoNTc3KR9DaHJpc3RpbmEgQmxvc3NlciAtIENPNTA1OCAgKDEpHUNocmlzdGluZSBHYW1hcyAtIE1UMjA0OCAgKDEpHUNocmlzdG9waGVyIExvdmUgTU45MDcyICAoOTApIENocmlzdG9waGVyIFNlZGVyIC0gTVQyMDUyICAoODApH0NocmlzdG9waGVyIFdhcnJlbiAtIE9SMjUwICAoMCkZQ2hyaXN0eSBMb3dlcnkgQ0E1NDMgICg3KRpDaHVjayBIYXJ2ZXkgLSBNVDIwMjEgICgwKRdDaW5keSBBcm9sZCBNSTgwOSAgKDE3KRtDaW5keSBNY0NhbGwgLSBOVjIyMiAgKDEzMikZQ2luZHkgTWlyb24gLSBNSTc1MSAgKDMwKRxDaW5keSBTb3JlbnNlbiAtIE1JODEyICAoNjQpHENpcHJpYW5vIERlbGFjcnV6IENBNTc2ICAoMCkbQ2xhcmljZSBDYWR5IC1NVDIwMjIgICgxMDcpH0NsYXl0b24gU2lsdm9uZW4gLSBPUjIzMiAgKDI2OCkbQ29sbGVlbiBEZW5uaXMgLSBDQTM2OCAgKDEpIENvbGxlZW4gRnJhbmtsaW4gLSBXQTU1OCAgKDE2OTEpHENvbGxlZW4gSGFubmEgLSBXQTYwMiAgKDE3MSkcQ29sbGVlbiBIYW5uYSAtIFdBNjAyQSAgKDI3KR1Db2xsZWVuIEhhbm5hIC0gV0E2MDJCICAoMzc3KR1Db2xsZWVuIEhhbm5hIC0gV0E2MDJEICAoMjU3KRtDb2xsZWVuIEhhbm5hIC0gV0E2MDJFICAoNCkdQ29sbGVlbiBIYW5uYSAtIFdBNjAyRiAgKDIwMSkaQ29ubmllIE9ydG9uIC0gVVQ3MDE3ICAoMCkcQ3JhaWcgUmV5bm9sZHMgLSBDTzUwNDQgICgwKRxDdXJ0aXMgTWFkc29uIC0gT1IxNTcgICgzNTUpHEN5bnRoaWEgQnJ5YW50IFROMTAwNyAgKDQ0NykdQ3ludGhpYSBXcmlza2UgLSBDTzUwMTYgICgxNCkvQ3ludGhpYSBLaW5nIC0gTlYyMjlBIEluc3BlY3Rpb25zIGJ5IEtpbmcgICgxMikbRGFsZSBNb3J0ZW5zZW4tTU45MDM1ICAoNTUpGURhbGUgU2Nocm9lZGVyIE1JODExICAoMykdRGFuIEhhY2hlbmJlcmdlciBDTzU5MDIgICg2NCkbRGFuaSBFcmlja3NvbiAtIE1UMjA1MyAgKDQpG0RhbmllbCBCeXJuZSAtIE5WMjM0ICAoNjI2KRtEYW5pZWwgQ2xheSAtIFdBNTEyICAoMTI5NikcRGFuaWVsIERldmxpbiAtIENPNTA5MSAgKDgxKR1EYW5pZWwgRmFuY2hlciAtIE1JNzY1ICAoMTEzKRpEYW5pZWwgRmlzaGVyIC0gQ0E1ODcgICgwKRpEYW5uaSBIYW5raW5zIENPNTA2NSAgKDMwKRpEYXJsYSBDb3dhbiAtIE9SMjY0ICAoMTY4KRxEYXJsZW5lIFdhdHNvbiAtIE5ENjAwNyAgKDYpHURhdmlkIEFuZGVyc29uIC0gV0E1NjEgICgxODIpGkRhdmlkIENsZW1lbnMgLSBXQTU5MCAgKDMpGERhdmlkIERvcnIgLSBDQTU1MiAgKDQwKRxEYXZpZCBHYXJuZXIgLSBVVDcwMDIgICgxMDYpGkRhdmlkIEdhcm5lciBVVDcwMDJBICAoNDkpHERhdmlkIEplcm5pZ2FuIC0gS1kzMDUzICAoMSkZRGF2aWQgSm9uZXMgLSBVVDcwMTMgICg4KRtEYXZpZCBNb3JlYXUgLSBXQTUxNCAgKDc1NikbRGF2aWQgU25pZGVyIC0gS1kzMDAyICAoNjQpGURhdmlkIFNueWRlciAtIENBNTAwICAoMikaRGF2aWQgVmllcnMgLSBNVDIwNTQgICg1MSkYRGF2aWQgWW9yayAtIENPNTEwMSAgKDApMkRhdmlkIEJyYXNzZmllbGQsIEJyYXNzZmllbGQgTWFzb25yeSAtIElENTg3ICAoNDEpGURhd24gQ3JhZnRzIC0gT1IyNjcgICgxMSkcRGF3biBNY0dlcmFnbGUgLSBDQTQ2NSAgKDExKRlEZWIgSGFyc2NoZSAtIE5ENjAwOCAgKDApHURlYmJpZSBTYW5kZXJzb24gQ081MDM2ICAoNTUpHURlYmJpZSBTYW5kZXJzb24gQ081MDM2QSAgKDkpH0RlYmJyYSBNY0RhbmllbCAtIFROMTAwMyAgKDgyMikXRGViaSBKb25lcyAtIE9SMjM4ICAoMSkXRGVicmEgQ2FzaCAtIE5WMjYxICAoMCkaRGVicmEgTWlsbGVyIC0gQ081MDU3ICAoMCkfRGVuaWNlIEluZ3JhbS1SaW5kIC0gQ0E0NzEgICg4KRlEZW5pc2UgVmljZSAtIENPNTA5MCAgKDApF0RpYW5hIEJlbnR0aSBNSTgwNyAgKDkpE0RpYW5hIENsZXJtb250ICAoMCkdRGlhbmUgS29iZXJudXN6IC0gTU45MDQwICAoMSkdRGljayBIb2RuZWZpZWxkIC0gTkQ2MDA0ICAoMikYRGluYSBGcmFua3MgVE4xMDE2ICAoODkpGERpeGllIE1jS2F5IC0gTlYyMzIgICgyKRxEb2xseSBQbHVtbWVyIC0gS1kzMDQ2ICAoMTcpHkRvbmFsZCBQaGlsbGlwcyAtIE5WMjQwICAoOTQxKR5Eb25hbGQgU3RlcGhlbnMgLSBNVDIwMDkgICgyMikXRG9ubmEgUmVhZCAtIENBNTE0ICAoMikeRG9ubmEgU3R1YmVudm9sbCAtIE1JNzQ5ICAoNzMpHERvcmV0dGUgQ2xhcmsgLSBTRDgwMTAgICgxNSkeRG90dGllIEJyb29rc2hpcmUgVE4xMDA1ICAoNjYpHERvdWcgQnJvbGluZyAtIE1UMjA3MiAgKDEzNykYRG95bGUgV2lsc29uIEtZMzA1OSAgKDEpHkR3aWdodCBXdWxsd2ViZXIgLSBTRDgwMTEgICgwKRlFZCBNY0N1cmR5IC0gTVQyMDI0ICAoNjIpM0VkZ2FyIFNhbmNoZXogTUFHIEluc3BlY3Rpb24gTmV0d29yayAtIENPNTA4MiAgKDQ2KTRFZGdhciBTYW5jaGV6IE1BRyBJbnNwZWN0aW9uIE5ldHdvcmsgLSBDTzUwODJBICAoMTUpM0VkZ2FyIFNhbmNoZXogTUFHIEluc3BlY3Rpb24gTmV0d29yayAtIENPNTA4MkIgICg3KR1FbGFpbmUgV2lydGFuZW4gLSBNTjkwNzEgICg3KRlFbGxlbiBIZWFmbmVyLVNEODAwOSAgKDQpGUVsbGVuIEtub3VzIC0gQ081MDUwICAoMCkcRXJpYyBKZW5uaW5ncyAtIEtZMzAxMCAgKDI3KRtFdGhhbiBOZ3V5ZW4gLSBXQTUzMyAgKDQ3OSkVRkFYIElOU1BFQ1QgU0ZTICAoODMpG0Zlcmd1cyBXb29sbGV5IE1OOTA1NCAgKDkwKRxGbG9yZW5jZSBTYXZ1c2EgLSBDQTUzMyAgKDApGEZvbmcgSGVyIC0gTU45MDU2ICAoMjE2KR1GcmFuY2lzY28gR2FyY2lhIC0gQ0EzMzggICgwKR1GcmFuayBIZXJuYW5kZXogIENBNTkyICAoNTAyKRpGcmFuayBTYXVlciAtIEtZMzAyNyAgKDM0KSFGcmFua2xpbiBNY1BoZXJzb24gLSBXQTYwMSAgKDE4NykYRnJlZCBCdXJ0b24gLSBNSTgwMSAgKDUpH0dhcnRoIFNjaHVsdGhlaXMgLSBDTzUxMDAgICgxNykWR2FyeSBCZXJnIC0gV0E1NzYgICgxKRlHYXJ5IEdyb3ZlIC0gV0E1ODUgICg1NzcpGUdhcnkgTWFuc291ciAtIE5WMjYzICAoNCkcR2FyeSBNZWlkaW5nZXIgLSBNVDIwMjYgICg3KRdHYXJ5IFJvYmIgLSBOVjIxMiAgKDE0KRhHYXJ5IFNlYXJzIC0gQ081MDYzICAoMCksR2FyeSBLaW5nIC0gTlYyMjkgSW5zcGVjdGlvbnMgYnkgS2luZyAgKDIyNykdR2F5bGUgRGVua2Vuc29uIC0gTlYyNTQgICgyMikZR2VuZSBQb3VuZHMgVE4xMDIwICAoMzYzKS9HZW5lcmFsIE1haW50ZW5hbmNlIGFuZCBDbGVhbmluZyAtIE1JODA2ICAoMTEyKRpHZW9yZ2UgS2FobGVyIC0gQ0E1MzQgICgwKR1HZW9yZ2lhbm5hIEJhZGVyIC0gQ0E1NjIgICgxKRtHZXJhbGQgQm9ka2lucyBUTjEwMTcgICg5OCkbR2VyYWxkIExpbmtlIC0gTU45MDQ1ICAoOTEpGUdsZW5uIE1vb3JlIFROMTAwNiAgKDUxMCkZR3JlZyBIYWlsZXktIE9SMTU4ICAoNTAyKRlHcmVnIE1haGxlciAtIE1OOTAxMSAgKDApG0dyZWdvcnkgQnViZWNrIC0gQ0E1MjAgICg1KRxIYXJyaWV0dCBTd2FuayAtIENPNTA2MSAgKDApF0hhcnJ5IFNrZWVzIEtZMzAzNSAgKDApG0hlYXRoZXIgQnJ5bm4gLSBXQTU5MSAgKDE2KRtIZWF0aGVyIENyb3NlIC0gQ0E1MTggICg5NikcSGVhdGhlciBUaWFuZW4gLSBDQTUxNSAgKDM4KRlIZWlkaSBXZWJiIC0gT1IxNjEgICgxOTgpG0hlbGVuIEhhbGNvbWIgLSBLWTMwNjkgICgwKSZIZXJiZXJ0IE1pY2hhZWwgUXVhbmR0IC0gS1kzMDIwICAoMjg0KRtIb2xseSBTdWVyd2llciAtIE1JNzI4ICAoMCkaSXJlbmUgQmVsdGluY2stTUk4MTMgICgzOCkZSXJtYSBSaXZlcmEgLSBJRDU0MSAgKDEwKR5KYWNraWUgUm9iZXJ0c29uIC0gTVQyMDg1ICAoNikpSmFjcXVlbGluIEJyb29rcyAtIExhd3JlbmNlIC0gQ081MDk2ICAoMSkeSmFjcXVlbHluIFdhY2hvYiAtIENPNTA0MCAgKDIpGkphbWVzIEhvbGRlciBUTjEwMTQgICgzNDQpG0phbWVzIEtlb3VnaCAtIFdBNDg1ICAoMzIwKRlKYW1lcyBQYXR0ZW4gLSBDQTUzNyAgKDEpIEphbWVzIFJhdHpsb2ZmIElJIC0gQ081MDI1ICAoMTIpGUphbWVzIFdhcmQgLSBVVDcwMDAgICgzNykZSmFtZXMgV2lsbGlzIC0gQ0E1NDEgICgwKSNKYW1lcy9DaHJpc3RpbmUgSG9vdmVyIC0gQ0E1NzAgICgwKRtKYW1pZSBTdGVlbGUgLSBJRDU1MiAgKDU1OSkbSmFuIEJhcnRvc2lrIC0gTUk3MjQgICg0MzgpHEphbiBCYXJ0b3NpayAtIE1JNzI0QSAgKDMwOCkcSmFuIEJhcnRvc2lrIC0gTUk3MjRCICAoMzgxKRxKYW4gQmFydG9zaWsgLSBNSTcyNEMgICg0MzUpHEphbiBCYXJ0b3NpayAtIE1JNzI0RCAgKDM5NikcSmFuIEJhcnRvc2lrIC0gTUk3MjRFICAoMTI5KRpKYW5ldCBKb2huc29uLUtZMzAxOSAgKDEwKRtKYW5ldCBNY0NsdXJnIC0gS1kzMDY1ICAoMCkaSmFuaWNlIEdyZWVuIC0gS1kzMDM3ICAoNykcSmFuaWUgVHV0ZXdob2wtTU45MDM3ICAoMTEzKR1KYW5pbmUgU2FuZ2RlciAtIFdBNTUzICAoNDczKRpKYXJyZXR0IFdpbmcgLSBDQTU4MiAgKDE3KRhKYXNvbiBDbGFyayBPUjI3NSAgKDE1NikcSmFzb24gU2hlaW1hbiAtIE1OOTAxOCAgKDE4KRdKYXkgTWlsbGVyIENPNTA0OSAgKDE5KRdKZWFuIFNlaGljIC0gQ0E0MTkgICgwKRhKZWFuaSBXZXN0IC0gT1IyMDYgICg3OSkZSmVmZiBBZGtpbnMgLSBPUjI1OSAgKDU0KRlKZWZmIFBpenp1dG8gVVQ3MDE5ICAoMTYpHEplZmZyZXkgU3RvbGFyIFROMTAxNSAgKDI0MykcSmVuaWZlciBKb2huc29uIC0gTUk3OTAgICgwKR9KZW5uaWZlciBDYXN0YW5lZGEgLSBDQTQ5OCAgKDIpFUplbm5pZmVyIFN0YWduZXIgICgwKR5KZW5uaWZlciBXaWxsZXR0IC0gSUQ1ODIgICg0NikbSmVycnkgR2VyYmVyIC0gTlYyMTYgICg2MTYpGkplcnJ5IE9nbGVzYnkgLSBDQTUwNyAgKDApHUplcnJ5IFBlbm5lbGwgLSBNSTczNCAgKDE5OTcpGUplc3NlIEJhcm9rYSAtIE1JNzYwICAoMikcSmVzc2UgSG9zbGVyIC0gTVQyMDA2ICAoMjY1KRxKaWxsIEZhaXJiYW5rcyAtIE1OOTA2MiAgKDMpGEppbGwgVGhvbWFzIE1UMjA3OSAgKDE2KRlKaW0gQnJvc3NlaXQgLSBOVjI2NSAgKDIpGkppbSBFbWJlcnNvbiAtIE5WMjEwICAoMTMpG0ppbSBGcmlnc3RhZCAtIE5ENjAwMyAgKDM4KR1KbyBFbGxlbiBTaWx2YSAtIE9SMjYzICAoNDA0KR9Kb2FuIFF1aWNrc3Ryb20gLSBNTjkwMDcgICgyMTYpGkpvZGVlIE11cnJhaW4gS1kzMDE4ICAoMTkpG0pvZWwgUmFzdGVsbG8gLSBNSTc2MyAgKDExKRdKb2huIENoZW5nIC0gQ0E1MzYgICgwKRlKb2huIERlIEpvbmcgLSBDQTUwNCAgKDMpF0pvaG4gRGUgTGVvbi1DQTYwNiAgKDApGkpvaG4gR2FtYmxlIC0gT1IyNDcgICgzNDIpHEpvaG4gR29uc2FsdmVzIC0gQ0E0ODIgICgyNCkZSm9obiBMb2Z0dXMgLSBDTzUwMzQgICgwKRpKb2huIE1jRG9uYWxkIE1OOTAzMiAgKDIzKRtKb2huIE1pcmFuZGEgLSBOVjE4OCAgKDM5MSkYSm9pIFNpbXBzb24gTU45MDU3ICAoMzApGEpvbiBSeXBkYWhsIC0gV0E1OTkgICgxKRhKb3JkYW4gQ2xhcmsgVE4xMDE4ICAoMCkYSm9zaCBGYWdhbiAtIE1OOTA1OSAgKDApHEp1YW4gR29uemFsZXogLSBDQTQ4NiAgKDE3NikdSnVhbiBHb256YWxleiAtIENBNDg2QSAgKDIwMikXSnVsaWUgTGVzbGllIElENTg2ICAoMSkaSnVsaWUgQSBUcm95IC0gTVQyMDMwICAoMCkZS2FuZGkgTXVycmF5IC0gQ0E1NjkgICgwKRhLYXJlbiBCYXllcyAtIE9SMjQwICAoNSkaS2FyZW4gRWxsaXMgLSBNSTcyMCAgKDE3NSkYS2FyZW4gUmVlZCAtIENPNTA3MyAgKDApHUthcmVuIFJvaXRidXJkIC0gTlYyMDIgICg2MTkpG0thcnkgQW5uIFN0YW5nZXIgQ0E1OTMgICgyKRlLYXRleSBXaGl0ZSAtIE1UMjA4MSAgKDEpHUthdGhsZWVuIEpvaG5zb24gLSBJRDU4MyAgKDEpGEthdGhyeW4gSGlsbCBJRDU4OSAgKDI2KRpLYXRoeSBHcmF5YmVhbCBNVDIwNzggICgyKRdLYXRoeSBXZXNsZXkgQ0E1NDUgICgwKR1LYXRoeXJuIFNhbmRlcnMgLSBNVDIwNTkgICgwKRhLYXlsYSBBZGFtcyAtIElENTUxICAoMCkbS2VpdGggT2dsZXNieSAtIE5WMTk5ICAoNDQpF0tlbGx5IEdvcmUgLSBDQTQ3MCAgKDApHktlbm5ldGggTW9uc29uIC0gTkQ2MDAyICAoMTYwKRlLZW50IE1lZWtlciAtIFdBNTIyICAoMjcpJ0tpbGxpbmdlciBFbnRlcnByaXNlcyBMVEQgLSBJRDU4NCAgKDQ0KRhLaW0gQ3JpcHBzIC0gTVQyMDE4ICAoMikaS2ltIEN1dHNmb3J0aCAtIE9SMjcwICAoMSkXS2ltIEZseW5uIC0gTVQyMDM2ICAoMykdS2ltIEthcmFsb3ZpY2ggLSBDTzUwNzkgICgyNykgS2ltYmVybHkgQm9ldHRnZXIgLSBNVDIwODMgICgyOCkbS2l0IFJvYmVydHNvbiAtIENPNTA3MCAgKDApJEtvb21lbiBFbnRlcnByaXNlcyBMTEMgLSBNSTc5OCAgKDEwKRtLcmFpZyBUaG9tcHNvbi1NTjkwNzUgICgzNCkcS3JpcyBCaWVzc2VuZXIgLSBNTjkwNjkgICgwKRhMYURhdW4gUmF5IC0gVVQ3MDE1ICAoMikcTGFuY2UgUG93ZWxsIC0gT1IyMjcgICgxNjA4KRtMYXJyeSBBbmRlcnNvbi1NTjkwNTMgICgyMSkbTGFycnkgRXNsaWNrIC0gTVQyMDM3ICAoMjIpGExhcnJ5IE5hZXJ0IC0gTlYxNjkgICgzKRtMYXJyeSBOYWVydCAtIE5WMTY5QSAgKDQ0OSkZTGFycnkgTmFlcnQgLSBOVjE2OUIgICg0KRpMYXJyeSBXaWxrZSAtIE1UMjAxNSAgKDEyKRxMYXJyeSBZZWxpbmVrIC0gTUk3OTMgICgxMTcpGUxhdXJhIENhc2UgLSBDTzUwMjAgICg0NSk2TGF1cmEgU3R1YXJ0IFRoZSBSZWFsIEVzdGF0ZSBTb2x1dGlvbiBHcm91cCBDQTU5MSAgKDApGExlYWggTGF3dG9uIC0gTlYyMDMgICg0KRtMZUFubiBWb2xsbWVyIC0gTkQ2MDE2ICAoMykZTGVlIENvYXRlcyAtIE5WMjEzICAoNTE1KRpMZW9ub3IgU2F5bG9yIC0gQ0E1NTQgICgxKRhMZXMgUm9sZmUgLSBNSTgwMCAgKDQ1MikSTGVzbGllIEJhcmxvdyAgKDApG0xpbmRhIEJ1dGxlciAtIEtZMzAwNCAgKDYxKRpMaW5kYSBGcmVjaGluIC0gQ0E1MTYgICg2KRpMaW5kYSBHYXJjaWEgLSBDQTM2NCAgKDE1KRhMaW5kYSBLaW5uIC0gTkQ2MDExICAoMykZTGluZGEgU2F5bGVzIC0gTUk3NjQgICg4KRtMaW5kc2V5IFdpbmcgLSBDTzUwOTkgICgzOCkRTGlzYSBDYXJyb2xsICAoMCkaTGlzYSBEcmlzY29sbCBNVDIwODYgICg5MSkWTGlzYSBLaWRkIC0gQ0E1MjMgICgwKRhMaXNhIE1vb3JlIC0gT1IyNjkgICg5NCkZTGlzYSBQaXJrbGUgLSBOVjIwMSAgKDcwKRlMaXNhIFJ1Z2dpZXJpIENPNTAyNyAgKDMpFkxpc2EgVmFzaGVyIE1JNzkyICAoOCkeTG9sZXR0YSBTdHJhdHRvbiAtIE9SMjYxICAoNjMpHExvcmV0dGEgQWxsZW4gLSBTRDgwMTIgICg0NykdTG9yZXR0YSBCcmFudG5lciAtIElENTg1ICAoMCkaTG9yaSBCYXNzZXR0IC0gSUQ1MzcgICg4NSkdTHUgQW5uIFNjaGVlcmVyIC0gTUk3NjcgICgxMykXTHVwZSBKYW1lcyAtIENBNDUxICAoMCkdTHluZXR0ZSBWZXJob2x0eiAtIENBNTY2ICAoMCkfTHlubiBDcnV0Y2hmaWVsZCAtIENPNTAxOSAgKDMyKRlMeW5uIEplbnNlbiBDTzUwODYgICg1MzEpGEx5bm4gTW9ydG9uIC0gQ0E1MDUgICgxKRxMeW5uZXR0ZSBHaWxlcyAtIE1JNzU5ICAoMTQpH0x5c2FuZHJhIFdpbGxpYW1zIC0gQ0E0MjcgICgxMikaTWFkaXNvbiBDb3ggLSBLWTMwMzYgICgyMikaTWFyYyBCZWJvdXQgLSBOVjI1MSAgKDMxNCkdTWFyZ2FyZXQgSGF5ZGVuIC0gQ081MDM4ICAoNCkeTWFyZ2FyZXQgTWNDbGVhbiAtIENBNDkwICAoMTEpGE1hcmdpZSBDcmlzcC1LWTMwMTcgICgzKR1NYXJnbyBHb29kaGV3IC0gS1kzMDcxICAoMTM4KRdNYXJpIEtlc2xlciBVVDcwMTIgICgxKRpNYXJpYSBWYXJnYXMgLSBDQTU4OCAgKDI3KRpNYXJrIEFuZGVyc29uIC0gT1IyMzMgICgwKR1NYXJrIEFuZGVyc29uIC0gT1IyMzNBICAoMzA1KRtNYXJrIEFuZGVyc29uIC0gT1IyMzNGICAoNSkcTWFyayBDdW5uaW5naGFtIFROMTAxMiAgKDc5KRxNYXJ0aW4gT2xzc29uIC0gTlYyMjYgICg0MTIpDk1hcnkgR3JheSAgKDApG01hcnkgUGV0ZXJzb24gLSBNTjkwMDggICg1KRtNYXJ5YW5uZSBDb3JkbyAtIE5WMjE4ICAoMCkZTWF0dCBSb2JlcnRzIFdBNTk1ICAoNDg1KRRNQ1MgSW5zcGVjdGlvbnMgICgwKR1NZWNoZWxsZSBNYWxvbmUtTU45MDY1ICAoMjg4KR5NaWNoYWVsIENoaWxkZXJzIC0gQ081MDAwICAoNSkgTWljaGFlbCBGYXJpbmVsbGEgLSBNTjkwNzAgICgxMCkbTWljaGFlbCBIb2tlIC0gT1IyMzQgICg3OTEpHk1pY2hhZWwgTWF0dGVybiAtIE1OOTAwNSAgKDI5KR9NaWNoYWVsIFBhdHRpc29uIC0gV1k0MDA1ICAoNTYpGk1pY2hhZWwgU2hhdyAtIENPNTA3MiAgKDApGk1pY2hlbGUgT3dlbiAtIENPNTA2MCAgKDQpHk1pY2hlbGxlIEFsd2luZSAtIElENTE4ICAoMzE5KRxNaWNoZWxsZSBCYXNoYW0gLSBDQTU4NiAgKDApHU1pY2hlbGxlIEhld2l0dCAtIFdBNTc4ICAoMTEpGk1pa2UgRG91Z2FsIC0gSUQ1MjMgICg2NTcpGk1pa2UgRm93bGVyIC0gT1IyMTIgICg3OTcpGk1pa2UgRnVsa2Vyc29uIENBNjE0ICAoMTQpG01pa2UgTGF3cmVuY2UgVE4xMDExICAoNjc5KRpNaWtlIE1ldHpnZXIgLSBVVDcwMTEgICgzKRdNaWtlIFJ1cHAgLSBNTjkwNTggICg5KRlNaWtlIFNtaXRoIC0gV0E2MDUgICg5NDgpEU1pbm5pZSBNb3VzZSAgKDApGk1pdGNoIFVtYmFyZ2VyIFROMTAyMyAgKDApG01vbGx5IFN0ZXZlbnMgLSBVVDcwMDkgICgwKRpNb25pY2EgV3JpZ2h0IC0gQ0E0NTYgICgxKRhNb250YW5hIEluc3BlY3Rpb25zICAoMCkZTXVyaWVsIEh1cnQgLSBORDYwMTIgICgxKRlOYW5jeSBCaXZlbnMgVE4xMDIyICAoNDcpGU5hbmN5IEphcmsgLSBTRDgwMTQgICgxMSkYTmFuY3kgTWltcyAtIEtZMzA3MCAgKDEpJk5hbmN5IFB5a2VybWFuIC0gTWFydGVucyAtIENPNTA2MiAgKDApHE5hbmN5IFNhbmdkZXIgLSBXQTU0OCAgKDExOSkcTmFuY3kgU2luY2xhaXIgLSBVVDcwMDEgICgwKRlOYXRoYW4gR2FtYmxlIENBNjAzICAoMTUpGU5heWxlbmUgTmllbGQgVVQ3MDAzICAoMCkrTmVscyBHcmFmc3Ryb20gUGFobGVuIFJlYWx0eSAtIE1OOTAyOCAgKDI1KR1OaWNreSBCbGFja3dlbGwgLSBPUjI0MSAgKDE0KRdOb3JhIEJ1cmNoIC1NTjkwMzggICgwKRlQYWlnZSBPZWRpbmcgLSBJRDU0OCAgKDApGVBhbSBEb3duZXkgLSBOVjE4MSAgKDI1MSkaUGFtIEpvaG5zb24gLSBLWTMwNTQgICgyNCkbUGFtZWxhIEphY2tzb24gLSBJRDU0NyAgKDIpHFBhbWVsYSBNb250ZXogLSBNSTcxOSAgKDI1NCkXUGF0IFdyaWdodCAtIElENTA0ICAoMCkfUGF0cmljaWEgSm9obnN0b24gLSBDQTU3OSAgKDMxKR5QYXRyaWNrIEdyaXNoYW0gLSBOVjI0NyAgKDkxNykeUGF0cmljayBSYWZmZXJ0eSAtIE5ENjAxNyAgKDQpHFBhdHJpY2sgU2F1bXVyZSAtIENBNTcyICAoMCkYUGF0c3kgV2FpdHMgLSBOVjI2MiAgKDEpGFBhdWwgTWFkaXNvbiBNSTgxMCAgKDIyKR1QYXVsYSBCYXJpcXVpdCAtIFdBNTYwICAoMjEwKRpQZWdneSBNaWxsZXIgLSBJRDUzOCAgKDIxKRlQZXRlciBQYXJpcyAtIFdBNDUwICAoNzgpFFF1YWxpdHkgQ29udHJvbCAgKDApIFJhY2hhZWwgS2ltYmVybGluZyAtIE1UMjA1MCAgKDMpGlJhY2hhZWwgU2VlbHllIFdBNjA3ICAoMTEpHFJhaW5lbGxlIE1jS2lubmV5LU5WMjY0ICAoMikgUmFuZHkgQmlyZHdoaXRzdGxlIC0gS1kzMDQzICAoMCkaUmFuZHkgWXVoYWxhIC0gTU45MDE5ICAoMikdUmVnaW5hbGQgRG9yc2V5IC0gQ0E0MTggICgyNCkYUmVuZWUgV2hpdG1hbi1DQTYwNSAgKDIpGlJoYW5lIFdpZG1hciAtIE9SMjY4ICAoNTUpFlJpYyBHZXJpZyAtIFdBNTcyICAoMykgUmljaGFyZCBCZW5pbnRlbmRpIC0gQ081MDQ4ICAoMCkZUmljaGFyZCBHaWZ0IC0gQ0E0MDIgICgwKRtSaWNoYXJkIExhdmlrIC0gTkQ2MDE4ICAoNykbUml0YSBUYWhtYXNpYW4gQ0E1OTcgICgxNTQpFlJvYiBHcmFoYW0gQ0E1OTQgICgyNCkYUm9iZXJ0IEVsbGlzLU5ENjAyNCAgKDApHVJvYmVydCBJc2FhY3NvbiAtIENPNTA2NyAgKDApHFJvYmVydCBNYWlvY2NvIC0gQ081MDk4ICAoMCkZUm9ieW4gTXllcnMgQ081MDg4ICAoMTc1KRxSb2xhbmQgRmFzc2V0dCAtIENBNTQyICAoMzEpGVJvbiBIYW5zb24gLSBNTjkwNTAgICg3NykZUm9uIFNwYXJrcyAtIE5WMjIwICAoOTQ3KRlSb3NlIEx1dHogLSBTRDgwMDcgICgxMzApHVJvc2VtYXJpZSBNdXJyYXkgLSBDQTU2NyAgKDApGFJveSBIb2xpZGF5IC0gQ0EzNTIgICgxKS9SdWJpZW4gQnJhbmRvbiBDb3VudHJ5IFJlYWwgRXN0YXRlIC0gQ0E2MTMgICgxKRtSdXNzIEdyb25lcnQgLSBOVjE2MyAgKDExMCkbUnVzc2VsbCBIb3Juc2J5IEtZMzA3MiAgKDMpGFJ1dGggQnVsbGVuIC0gTUk3NjggICgzKRlSdXRoIFJhYm9sZCAtIE1OOTAyOSAgKDMpF1J5YW4gRWF0b24gSUExMDAwMCAgKDApHlJ5YW4gR3JhdWJlcmdlciAtIE5WMjUwICAoMzU2KRhSeWFuIFdlYmIgLSBOVjIxNyAgKDIwMykXUnllIE5pZWxzb24gVVQ3MDA3ICAoMCkcU2FicmluYSBQb3J0ZXIgLSBDQTQ5NiAgKDYxKRZTYW0gSGFobiBTRDgwMTUgICgxMjcpGVNhbmRyYSBPZ2xlIFROMTAwNCAgKDU0NykfU2FuZHJhIFdlZGRpbmd0b24gLSBLWTMwNjIgICgzKRJTYW5keSBQaWxncmltICAoMCkbU2NvdHQgS2VubmVkeSAtIE1UMjA2OCAgKDApG1Njb3R0IExpYmVydHkgLSBOVjIzNSAgKDE0KRdTY290dCBMeW5jaCBDQTYwOSAgKDMxKR1TY290dCBSdXRlcmJ1c2NoIC0gTUk3ODcgICgxKRdTY290dCBUYXlsb3IgQ0E2MTIgICgwKTJTY290dCBTY2hsb3NzZXIgUmVhbCBFc3RhdGUgU2FsZXMgTExDLUNPNTA5NCAgKDI5KRtTZWFzb24gS2lsZ29yZSAtIE5WMTk0ICAoMCkdU2VsZW5hIE1jTmVpbGwgLSBPUjI0MiAgKDExMykaU2hhbmUgR2lic29uIC0gTVQyMDY2ICAoMikYU2hhbmUgT2dkZW4gLSBJRDU4MCAgKDUpGlNoYXJhIFNodW13YXkgLSBPUjI0MyAgKDApElNoYXJpIExhbWJlcnQgICgwKRdTaGFyb24gQmVlbi1DTzUwNjQgICg1KRlTaGFyb24gV2FkYSAtIElENTQzICAoOTMpHFNoYXJvbiBXb21ib2xkIC0gTVQyMDQzICAoMikaU2hheW5lIEhvbGxhbmQgVE4xMDI0ICAoOCkcU2hlaWxhIFJpY2h0ZXIgLSBNTjkwMjIgICgxKRxTaGVsbHkgRXZhbnMgLSBNVDIwODQgICgyMDApGlNoZXJyeSBNb29yZSAtIElENTQyICAoMjEpEVNoZXJ5bCBIb2RnZSAgKDApHlNoaXJsZXkgU2FkZG9yaXMgLSBDTzUwNTQgICgwKR9TaGlybGV5IFN0ZXBoZW5zIC0gTVQyMDA3ICAoNDApHFNwZW5jZXIgU21pdGggLSBXQTU0OSAgKDMzNSkeU3RhbnRvbiBNY0RhbmllbHMgLSBXQTUxOSAgKDcpGVN0ZWZhbmllIEJhaHIgTVQyMDg3ICAoMikdU3RlcGhhbmllIEpvbmVzIC0gTVQyMDY1ICAoMSkhU3RlcGhlbiBGdXJzdGVuZmVsZCAtIENPNTA0NSAgKDApHFN0ZXZlIEplbmljZWsgLSBNVDIwNzUgICgzMSkaU3RldmUgTWlsbGVyIC0gQ081MDU1ICAoMCkbU3RldmUgTWlsbGVyIC0gV0E0NTQgICgzODYpGFN0ZXZlIFRvbXMgLSBDQTM1NSAgKDQ4KR5TdGV2ZW4gTWFjQXNraWxsIC0gSUQ1NjEgICg2MykeU3RldmVuIFNhbmRlcnNvbiAtIE1JNzQzICAoMjMpGlN0ZXdhcnQgS2luZyAtIE9SMjU0ICAoMTgpGFN1ZSBCcmV3ZXIgLSBDQTU1NyAgKDEwKRtTdXNhbiBQb3dlcnMgLSBNSTc0MiAgKDIxMSkeU3VzYW4gVmFuIEdvcmRlbiAtIE1OOTA1MSAgKDkpHFN1c2FuIFdoaXRlbG9jayAtIENBMzYzICAoMCkbU3V6YW4gUGVsbG9uaSAtIENPNTA1OSAgKDApHlN1emFubmUgQ291bHRlciAtIE1OOTA2OCAgKDkyKR1TdXphbm5lIEt1dXNpbmVuIC0gTUk3NjkgICgzKR9TdXphbm5lIExhbmNlLUR1YXJ0ZS1DQTYxMCAgKDQpF1RhbWkgV2l0dCAtIENPNTA1NiAgKDApG1RhbW1pZSBTaG9ja2xleSBLWTMwNTcgICgzKRtUYW1teSBIdXRjaGlucyBDTzUwMzIgICg0NCkaVGFtbXkgTGF1ZXIgLSBNVDIwNDUgICgyMSkbVGFyYWggVmFuR3JvdXcgLSBDQTU4MCAgKDApGlRhdW5hIEJ1cmhhbnMgLSBOVjEwMiAgKDEpGFRlZCBOZWxzZW4gLSBPUjExMCAgKDY0KRpUZW5uZXNzZWUgSW5zcGVjdG9yICAoMTMwKRxUZXJlc2EgVXJpYXJ0ZSAtIE9SMjE4ICAoMjEpGlRlcnJpIEFka2lucyAtIEtZMzA2NCAgKDIpG1RlcnJ5IERlTWFycyAtIFdBNTc3ICAoMjE0KRxUZXJyeSBIb3BraW5zIC0gQ081MDA2ICAoNDUpElRlcnJ5IE5hdW1hbm4gICgwKRhUZXJyeSBRdWlyayAtIENBNTEwICAoMSkVVGVzdCBJbnNwZWN0aW9ucyAgKDEpGlRoYWQgTWNLYWluIC0gQ081MDc4ICAoMjkpHlRoZW9kb3JlIFdhZ25lciAtIE1JNzE3ICAoMTk5KR9UaGVvZG9yZSBXYWduZXIgLSBNSTcxN0EgICgxNTApIlRoZXJlc2EgRm9sdHotRm9ycmVzdCAtIENBNDU0ICAoNykbVGhlcmVzYSBHcmltc2hhdyBDQTU0NiAgKDEpGlRob21hcyBCcm93biAtIEtZMzA0MCAgKDgpGlRob21hcyBTbWl0aCBUTjEwMTAgICg1ODgpJVRob21zb24gJiBUaG9tc29uLCBJbmMuIC0gVVQ3MDE2ICAoMykXVGltIERhdmlzIC0gQ0E1MTIgICgyNykZVGltIEhhbnNlbiAtIFdBNDE4ICAoNDQ5KRpUaW0gS2VlbmFuIC0gTU45MDAzICAoNDk3KRdUaW0gTWNDb3kgLSBLWTMwNDQgICg2KRlUaW0gU3RvbmUgLSBXQTU5NyAgKDQxMjYpHVRpbW90aHkgS2VubmVkeSAtIE1OOTAzNiAgKDApHFRpbmEgQW5kZXJzb24gLSBNTjkwNjYgICgzMikaVGluYSBXdXJzdGVyIC0gTlYxODcgICgzNCkaVG9tIE1jTmVpbGwgLSBXQTYwOSAgKDE1NCkWVG9tIFdhbGwgVE4xMDEzICAoMjYwKRxUb25hIEplbmtpbnMgLSBOVjIwMCAgKDE1NDApGlRyYWN5IEJ1dHprbyAtIFdBNTA2ICAoMjIpL1RyaS1Db3VudHkgUmVhbHR5IEluYy4gS3lsZSBIYXR0b24gLSBDQTYxMSAgKDApEVRyaWNpYSBEZW5ueSAgKDApEVRyaWNpYSBEZW5ueSAgKDApElRydWR5IE5hdW1hbm4gICgwKRJUcnVkeSBOYXVtYW5uICAoMCkaVHlsZXIgRHVubmluZyAtIENBNTU4ICAoMCkaVHlyb25lIEJ1bGxvY2sgQ0E2MDIgICgxMSkcVmlja2llIFRpZHdlbGwgVE4xMDA5ICAoNzI2KRtWaWN0b3IgS2FuZGxlIC0gT1IyMDMgICgxMSkdVmljdG9yIEthbmRsZSAtIE9SMjAzQSAgKDIwMikeVmljdG9yaWEgSGFzc2xlciAtIE5ENjAyMyAgKDApHVZpb2xldCBLb255aGEgLSBXWTQwMDMgICg0NTQpHVZpcmdpbmlhIENvcmRlcyAtIE5WMjA1ICAoNjEpGldhbHRlciBNb3JyaXMgLSBDQTU3NyAgKDYpHFdlbmR5IEpvaG5zb24gLSBNTjkwMzQgICgxMCkcV2VuZHkgTWV0Y2FsZiAtIFdBNTIwICAoMjg0KRlXZXNsZXkgS2lzZXIgS1kzMDQ5ICAoNjEpHVdpbGwgSGFtbWFybHVuZCAtIE1OOTAwNCAgKDApG1dpbGxpYW0gQWRhbXMgLSBLWTMwMzkgICgwKRpXaWxsaWFtIEhvcm4gLSBLWTMwNjYgICg0KSBXb3JsZCBQcmlvcml0eSwgTExDIC0gQ0E1NDAgICgwKSFXb3JsZCBQcmlvcml0eSwgTExDIC0gQ0E1NDBCICAoMCkcWXZvbm5lIEhhbm5lbWFuIC0gQ0E1MjUgICgxKRWyBAABMAItMQQ5NDg2BDg0NTQENDg3MQUxMjEwOQQ5NjQ4BDkzNDcENDkzMgUxNDA3NAQ0MzY5BDQyNDcENTQ5OQQ1NTAwBDU1MDEENTUwMwQ0MjM1BTEyMTU4BDg0NDIFMTA5MjQFMTA2OTIFMTQyNTQFMTI3OTQFMTI3OTUFMTQwNzkENDM4MAUxMTE0MAQ0MzAwBDQzNjYENzgwMgQ3NjIxBTExOTc3BDQ0MTcFMTA1MDUFMTAzNTQEOTU0NgUxMzU5MwUxNDI0NwUxMTk4MgQ4MjY1BDQyOTkEODUxMwUxMTE3NAUxMDA5OAQ3OTQwBTEwNzc5BDMyODIENTQ5NwUxNDI1MwQ4NTc4BDQ3MDQFMTI3OTIENzk0MQUxMDczMgUxMDI1OAQ1MzA1BDQyNjkEOTk3OAQ0NDkyBTEwODAzBDgxMjgEODI5NAQ0NjczBDQ5MzMENTUxOAUxMDk2MQQ0MzYyBDk0NzUEMzE5OQQ0MTcxBTE0MTEyBDMzMTkENzI4OAQ0NDA1BTEwNjIyBDg1MDkENDU1MwQzMzE3BDgzNDQEMzg4NgUxMDc1MAUxMDg2MgQ0MjI3BDMxODcENDY5MwUxMTM1OQQ4OTUwBDkwNjQFMTEzMzEEODg5OAQ5MTM3BDQyNTQEODk0OQQ1MDI2BTExNTUwBDQ5MDYENTM5NQQ3OTcxBDQzOTQFMTI3NDgENDM4MQQ0NzAwBTEzOTAwBDk0ODMENDUyOQQ0MjkxBDQyNDYENDI1MwUxMDA4MgUxMDE4NwUxMDE4OAUxMDE5MAUxMDE5MQUxMDgxNAQ5ODM2BDgyNjMEMzMwNAUxNDEwNAQ3NjgxBDY4ODQFMTA4NjcFMTM4MDUFMTE4NzcENDg1MQQ3ODA2BDMzMDkFMTE4NTEENDcxMQUxMDYzMQQ5MTc4BDg4NzEENDU1NwQ0MzUxBDczMzkEODI5MwQ3OTk2BTEwNjYwBDg5MzAEODc2MwQ0MjgyBDg0NTUENTAwMAQ0ODYwBTE0MjE2BTExOTgzBDk0NzcENDI3OQQ0NTU4BDgwNjIFMTA2MjcFMTQwNzgENDQ3OQUxMDUyNQQ4ODkzBDQyNjgFMTE3OTcFMTIwNjQEMzg1MgUxMDkxMQQ0MzU2BTE0MjA2BDc1NDkEODc4OQQ4NzYyBDQwNjUENjgxNAQ0Njk5BDk4ODYFMTQxMDEEODgyOAQ5MTMxBDk5ODgENDM5NwUxMTM2OAUxMjYxNAUxMjYxNQUxMTUyMQQ4NTAwBDg0MjcEODQ4MgQ0Mjg0BDQ0MzIFMTEwMjUENzYzNgUxMTAzMQQzMjI4BTExMzYwBDg1ODEFMTAwNTgEOTExMAUxMzgzMwQ0NTMyBDcwMjEFMTI1NjAENDM5NgQ0MTg1BDkxMDEENjg4MwUxMDEzOQUxNDI1MgUxMTE5NQQ3NjQyBDg1NzYFMTQyMTcFMTA5NTcFMTQxMDgEMzMwMgUxMDczOAQ3MzA5BDkwMzcEODU5NQQ3NDI0BDcyMjcENjgzMgQ0MzAxBDk5NzkEODUzMAQ0NjY4BTE0MjE5BDMyODUFMTAxNTkFMTI3OTMEODIxMgUxNDE4OAQzMzE2BDc2NzEENzkwMQQ3OTc1BDc4NTgEOTIwMAQ0MjE0BDQ2NjUENDY2NgQ0NjY3BDkyMjIEOTc1MwUxMDU3NAQ4NTExBDkzODAEODYxMwUxMTEzNgQ0Mjg4BTEwMTk1BTEyNzUxBTEwNzc2BDgxNzAEMzI1OAQzMzA2BDczNDkFMTI5MDcFMTQxODkEOTQ3MwQ0OTk4BDM4NjAEODc1NgQ0MTg4BDQ5NjgENDY5MQQ0NzA2BDQyMTEFMTExNDgEOTEzNAUxMzgwNwQ0MTgzBDQyMTgEODg0MAUxMDcyNAQ4NTA4BDQ3MDkENzY1NAQ1MjA1BTEyODM0BDUyNjUENDI1OQQ3OTkwBTEwODQwBDQxNzkFMTEwNDYEOTIzNAUxNDIxOAUxMTEyNgQ0MjYwBDczMjAFMTA5NjAENDQwMwQ5MDY3BDQ0MTEENDY2NAQ5NzU5BDMyMDAFMTEzNjkEOTM2NwQ5OTY5BTE0MjEyBDkxMzAEODE5NgQ1MDI1BDQyMzQEMzE5NwQ0MjYxBDQyMjAENDI4MAUxMDYwOQQ0MzkxBDk3MTEENDM5MwUxMDQwOQQ5NzM0BDk2NjcFMTA2MzAFMTIxMjYFMTEyMTcEOTQ0NgQ0Mjg2BTExMDIxBDQ0NDYEMzE5NgQzMTk1BDY5MTMENDM1NAQ5ODcxBDc4MjgFMTEzNDgEMzE5MgQ1MDIxBDQxODYEODMxMQQ1MzIwBDQ2MjYEODQ1OAQ2OTY5BDQyNTYENDQyNgQ0NzEwBTEzNTk1BDQxNjAFMTIyMTcENzM3MAQ5NTI4BDQxODEENzkwMwQ5NTkwBDgyMzEFMTAzODIFMTA5MjkEMzI3NwQ0NTI1BDMyMzkEODk1MQQ3NzIzBTExNzMwBDQ4ODkENDcwNQQzMjcwBDg2MTEEOTg2NQQ4MTU5BDQyNzcEODUwMwUxMDAyNwQ4NzE2BTEwNjUwBDQzMzMENDMzNQQ4MjMwBTE0MTY3BDUwNjIEMzk5OAUxMDcyNQQ0NjAwBDgxMTkENzU3MAUxMTE3OAQ3NTc4BTExNTE1BDQyNjQFMTA3MDgENDEzOQQ5NzQ2BDkwMzAEMzI3NQUxMDYxMgQ2MzczBDQyMDgENDM2MQUxNDI3NwUxNDE2OAQ4NjI2BTExMDc2BTExNTE0BDY4ODkFMTQyNjYEODU0NQQzMjczBDcwMDEENDM4NwUxNDI2NQUxMTQ2NgQ5OTgwBDkwNTIENDI4OQQ3OTkyBTEyNTY0BDgwMjIFMTA4MTMENDM4NAUxMDkwNgQzMjc2BDMxODMEODk2MgQzMjgxBDQ2NjMEMzI4OAUxMDA2OQQ5NzQ3BDUwMDMEOTIyMwUxMTUxNgUxMzQ0NAQ0MzYwBDMyODQEMzMyMAQ5NTA0BDUxNTcFMTMxNzcFMTM0NjgEODc3NQUxMDc3NwQzMjIwBTEyNjg2BDk0ODcENDQwNAQ4MzYxBDQyNTgENTAyMgUxMTgwMgUxMTU4MwUxMzc3NgQ5Mzc4BTEzNTE2BTExNzYxBDc5NTEFMTA5ODMENDU4NwQ0NTM4BDg5NTUENDI2NgUxNDA4MAQzMTg2BTEwMzI2BDQ1MjYFMTA4MjIFMTQxNDAEOTg1MAQ0NTY3BDgzNjIENDg5MAUxMjM5NwUxNDA4NAQ5MjY0BDc4MjIEODU3NQQ4MTI5BTEzNzQ1BDY3MDIFMTM5NzkFMTIyMTgEMzE4OQQ0NjE2BDc2NzMENzY0MwQ0NDgxBDM4ODcEOTE1NAQ0MjI2BDQ2MTcFMTQyNjcFMTA3ODAEOTkxMwQ0MjIzBDkxNDYEODgxNQQ0MDUxBDQyOTIENDI3OAUxMjYwMwQ3MDA5BDgyNjQEODkwOAQ4ODE3BDQyMjgENDQ1OAQ1Mzc3BDQ2OTgENTc2MwQ4MzYzBDQ2OTcFMTA5ODgENDMwMgQ4OTUyBTExMjA2BDQ1MjgFMTM4NzIEODg3MAQ5MDA3BDc5NzcENDYxMwUxMDA5NwQzMTgxBDQ5OTcFMTA2ODYEMzMwNQQ5MjY2BDU3NDAENzU5MQQ2OTYyBDUwNjMENzM0OAUxMDM2NQQ0NjYyBTEzNjM2BDQ0NzcEODIwMAQ4NjYyBTE0MTM3BDk1NjYENjc2NgQzMzE0BTEwNzA0BDg3NzYEODQ3OQUxMDkwMwUxMTE5NAQzMjA1BTEzNTk0BTE0MTcxBDMxOTQEMzMwOAUxMzkwMQQ3NzE5BDc3MjAEMjMzNgUxMDY4MQQ4Mzk5BTEyNTYyBTE0MTE4BDMzMDMENDE3MAQ5NzczBDQyMTIEMzE4MgQ5Njc1BTEwODY0BDU1MjIEODg2NQUxMDcwNwQ4NjYxBDk0NzYENzgxMQQ5OTY3BDc0MTgUKwOyBGdnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dkZAIsDxAPFgIfBGhkZBYAZAItDxBkEBUVA0FsbAROb25lAk1lE0FuZHJlYSBQaWxncmltICAoMCkbQmV2ZXJseSBNYXN0ZXJzLU1JODE0ICAoMjIpE0NhdGh5IE1haGFmZmV5ICAoMCkTRGlhbmEgQ2xlcm1vbnQgICgwKRVKZW5uaWZlciBTdGFnbmVyICAoMCkSTGVzbGllIEJhcmxvdyAgKDApEUxpc2EgQ2Fycm9sbCAgKDApDk1hcnkgR3JheSAgKDApEXFjIGR1bW15IHNmcyAgKDApFFF1YWxpdHkgQ29udHJvbCAgKDApElNhbmR5IFBpbGdyaW0gICgwKRJTaGFyaSBMYW1iZXJ0ICAoMCkRU2hlcnlsIEhvZGdlICAoMCkSVGVycnkgTmF1bWFubiAgKDApFVRlc3QgSW5zcGVjdGlvbnMgICgxKRFUcmljaWEgRGVubnkgICgwKRJUcnVkeSBOYXVtYW5uICAoMCkSVHJ1ZHkgTmF1bWFubiAgKDApFRUAATACLTEENDM2OQUxNDI1MwQzODg2BDM4NTIEMzg2MAQ0NjI2BDQxNjAEMzk5OAQ5Nzk3BDk1MDQENzgyMgQzODg3BDkxNDYENjk2MgQ3MzQ4BDc3MTkEMjMzNgUxMDY4MRQrAxVnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dkZAIuDxBkEBUcA0FsbAROb25lAk1lE0FuZHJlYSBQaWxncmltICAoMCkTQW5kcmVhIFBpbGdyaW0gICgwKRtCZXZlcmx5IE1hc3RlcnMtTUk4MTQgICgyMikTQ2F0aHkgTWFoYWZmZXkgICgwKRNDYXRoeSBNYWhhZmZleSAgKDApD0RhdGEgRW50cnkgICgwKRNEaWFuYSBDbGVybW9udCAgKDApFUplbm5pZmVyIFN0YWduZXIgICgwKRJMZXNsaWUgQmFybG93ICAoMCkRTGlzYSBDYXJyb2xsICAoMCkPTG9zcyBEcmFmdCAgKDApDk1hcnkgR3JheSAgKDApFFF1YWxpdHkgQ29udHJvbCAgKDApElNhbmR5IFBpbGdyaW0gICgwKRJTYW5keSBQaWxncmltICAoMCkSU2hhcmkgTGFtYmVydCAgKDApElNoYXJpIExhbWJlcnQgICgwKRFTaGVyeWwgSG9kZ2UgICgwKRFTaGVyeWwgSG9kZ2UgICgwKRJUZXJyeSBOYXVtYW5uICAoMCkVVGVzdCBJbnNwZWN0aW9ucyAgKDEpDnRvbyBlYXJseSAgKDApEVRyaWNpYSBEZW5ueSAgKDApElRydWR5IE5hdW1hbm4gICgwKRJUcnVkeSBOYXVtYW5uICAoMCkVHAABMAItMQQ0MzY5BDk2NTgFMTQyNTMENDg5NQQzODg2BDM0NTEEMzg1MgQzODYwBDQ2MjYENDE2MAQ3MDEyBDM5OTgEOTUwNAQ3ODIyBDQwOTAEMzg4NwQ0NjI1BDkxNDYEOTE1NQQ2OTYyBDczNDgENTQ4MgQ3NzE5BDIzMzYFMTA2ODEUKwMcZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2RkAjoPEGQPFgJmAgEWAhAFDFN1bW1hcnkgSW5mbwUBNmcQBRBKb2IgQ29udGFjdCBJbmZvBQIxMGcWAWZkAjsPEGQQFQwKU29ydCBPcmRlcghKb2IgTmFtZQZKb2IgSWQHQWRkcmVzcwZDdXN0b20FT3JkZXIPRGlzcGF0Y2hlZCBEYXRlDFJlcCBEdWUgRGF0ZRFXaW5kb3cgU3RhcnQgRGF0ZQ1Db21wbGV0ZSBEYXRlFU51bWJlciBvZiBBdHRhY2htZW50cwZTdGF0dXMVDAIxOAExATcBOAIxMwE5AjI0AjE0AjIwATICMTYBNRQrAwxnZ2dnZ2dnZ2dnZ2dkZAI9DxBkDxbJAWYCAQICAgMCBAIFAgYCBwIIAgkCCgILAgwCDQIOAg8CEAIRAhICEwIUAhUCFgIXAhgCGQIaAhsCHAIdAh4CHwIgAiECIgIjAiQCJQImAicCKAIpAioCKwIsAi0CLgIvAjACMQIyAjMCNAI1AjYCNwI4AjkCOgI7AjwCPQI+Aj8CQAJBAkICQwJEAkUCRgJHAkgCSQJKAksCTAJNAk4CTwJQAlECUgJTAlQCVQJWAlcCWAJZAloCWwJcAl0CXgJfAmACYQJiAmMCZAJlAmYCZwJoAmkCagJrAmwCbQJuAm8CcAJxAnICcwJ0AnUCdgJ3AngCeQJ6AnsCfAJ9An4CfwKAAQKBAQKCAQKDAQKEAQKFAQKGAQKHAQKIAQKJAQKKAQKLAQKMAQKNAQKOAQKPAQKQAQKRAQKSAQKTAQKUAQKVAQKWAQKXAQKYAQKZAQKaAQKbAQKcAQKdAQKeAQKfAQKgAQKhAQKiAQKjAQKkAQKlAQKmAQKnAQKoAQKpAQKqAQKrAQKsAQKtAQKuAQKvAQKwAQKxAQKyAQKzAQK0AQK1AQK2AQK3AQK4AQK5AQK6AQK7AQK8AQK9AQK+AQK/AQLAAQLBAQLCAQLDAQLEAQLFAQLGAQLHAQLIARbJARAFA0FsbAUBMGcQBQExBQExZxAFATIFATJnEAUBMwUBM2cQBQE0BQE0ZxAFATUFATVnEAUBNgUBNmcQBQE3BQE3ZxAFATgFAThnEAUBOQUBOWcQBQIxMAUCMTBnEAUCMTEFAjExZxAFAjEyBQIxMmcQBQIxMwUCMTNnEAUCMTQFAjE0ZxAFAjE1BQIxNWcQBQIxNgUCMTZnEAUCMTcFAjE3ZxAFAjE4BQIxOGcQBQIxOQUCMTlnEAUCMjAFAjIwZxAFAjIxBQIyMWcQBQIyMgUCMjJnEAUCMjMFAjIzZxAFAjI0BQIyNGcQBQIyNQUCMjVnEAUCMjYFAjI2ZxAFAjI3BQIyN2cQBQIyOAUCMjhnEAUCMjkFAjI5ZxAFAjMwBQIzMGcQBQIzMQUCMzFnEAUCMzIFAjMyZxAFAjMzBQIzM2cQBQIzNAUCMzRnEAUCMzUFAjM1ZxAFAjM2BQIzNmcQBQIzNwUCMzdnEAUCMzgFAjM4ZxAFAjM5BQIzOWcQBQI0MAUCNDBnEAUCNDEFAjQxZxAFAjQyBQI0MmcQBQI0MwUCNDNnEAUCNDQFAjQ0ZxAFAjQ1BQI0NWcQBQI0NgUCNDZnEAUCNDcFAjQ3ZxAFAjQ4BQI0OGcQBQI0OQUCNDlnEAUCNTAFAjUwZxAFAjUxBQI1MWcQBQI1MgUCNTJnEAUCNTMFAjUzZxAFAjU0BQI1NGcQBQI1NQUCNTVnEAUCNTYFAjU2ZxAFAjU3BQI1N2cQBQI1OAUCNThnEAUCNTkFAjU5ZxAFAjYwBQI2MGcQBQI2MQUCNjFnEAUCNjIFAjYyZxAFAjYzBQI2M2cQBQI2NAUCNjRnEAUCNjUFAjY1ZxAFAjY2BQI2NmcQBQI2NwUCNjdnEAUCNjgFAjY4ZxAFAjY5BQI2OWcQBQI3MAUCNzBnEAUCNzEFAjcxZxAFAjcyBQI3MmcQBQI3MwUCNzNnEAUCNzQFAjc0ZxAFAjc1BQI3NWcQBQI3NgUCNzZnEAUCNzcFAjc3ZxAFAjc4BQI3OGcQBQI3OQUCNzlnEAUCODAFAjgwZxAFAjgxBQI4MWcQBQI4MgUCODJnEAUCODMFAjgzZxAFAjg0BQI4NGcQBQI4NQUCODVnEAUCODYFAjg2ZxAFAjg3BQI4N2cQBQI4OAUCODhnEAUCODkFAjg5ZxAFAjkwBQI5MGcQBQI5MQUCOTFnEAUCOTIFAjkyZxAFAjkzBQI5M2cQBQI5NAUCOTRnEAUCOTUFAjk1ZxAFAjk2BQI5NmcQBQI5NwUCOTdnEAUCOTgFAjk4ZxAFAjk5BQI5OWcQBQMxMDAFAzEwMGcQBQMxMDEFAzEwMWcQBQMxMDIFAzEwMmcQBQMxMDMFAzEwM2cQBQMxMDQFAzEwNGcQBQMxMDUFAzEwNWcQBQMxMDYFAzEwNmcQBQMxMDcFAzEwN2cQBQMxMDgFAzEwOGcQBQMxMDkFAzEwOWcQBQMxMTAFAzExMGcQBQMxMTEFAzExMWcQBQMxMTIFAzExMmcQBQMxMTMFAzExM2cQBQMxMTQFAzExNGcQBQMxMTUFAzExNWcQBQMxMTYFAzExNmcQBQMxMTcFAzExN2cQBQMxMTgFAzExOGcQBQMxMTkFAzExOWcQBQMxMjAFAzEyMGcQBQMxMjEFAzEyMWcQBQMxMjIFAzEyMmcQBQMxMjMFAzEyM2cQBQMxMjQFAzEyNGcQBQMxMjUFAzEyNWcQBQMxMjYFAzEyNmcQBQMxMjcFAzEyN2cQBQMxMjgFAzEyOGcQBQMxMjkFAzEyOWcQBQMxMzAFAzEzMGcQBQMxMzEFAzEzMWcQBQMxMzIFAzEzMmcQBQMxMzMFAzEzM2cQBQMxMzQFAzEzNGcQBQMxMzUFAzEzNWcQBQMxMzYFAzEzNmcQBQMxMzcFAzEzN2cQBQMxMzgFAzEzOGcQBQMxMzkFAzEzOWcQBQMxNDAFAzE0MGcQBQMxNDEFAzE0MWcQBQMxNDIFAzE0MmcQBQMxNDMFAzE0M2cQBQMxNDQFAzE0NGcQBQMxNDUFAzE0NWcQBQMxNDYFAzE0NmcQBQMxNDcFAzE0N2cQBQMxNDgFAzE0OGcQBQMxNDkFAzE0OWcQBQMxNTAFAzE1MGcQBQMxNTEFAzE1MWcQBQMxNTIFAzE1MmcQBQMxNTMFAzE1M2cQBQMxNTQFAzE1NGcQBQMxNTUFAzE1NWcQBQMxNTYFAzE1NmcQBQMxNTcFAzE1N2cQBQMxNTgFAzE1OGcQBQMxNTkFAzE1OWcQBQMxNjAFAzE2MGcQBQMxNjEFAzE2MWcQBQMxNjIFAzE2MmcQBQMxNjMFAzE2M2cQBQMxNjQFAzE2NGcQBQMxNjUFAzE2NWcQBQMxNjYFAzE2NmcQBQMxNjcFAzE2N2cQBQMxNjgFAzE2OGcQBQMxNjkFAzE2OWcQBQMxNzAFAzE3MGcQBQMxNzEFAzE3MWcQBQMxNzIFAzE3MmcQBQMxNzMFAzE3M2cQBQMxNzQFAzE3NGcQBQMxNzUFAzE3NWcQBQMxNzYFAzE3NmcQBQMxNzcFAzE3N2cQBQMxNzgFAzE3OGcQBQMxNzkFAzE3OWcQBQMxODAFAzE4MGcQBQMxODEFAzE4MWcQBQMxODIFAzE4MmcQBQMxODMFAzE4M2cQBQMxODQFAzE4NGcQBQMxODUFAzE4NWcQBQMxODYFAzE4NmcQBQMxODcFAzE4N2cQBQMxODgFAzE4OGcQBQMxODkFAzE4OWcQBQMxOTAFAzE5MGcQBQMxOTEFAzE5MWcQBQMxOTIFAzE5MmcQBQMxOTMFAzE5M2cQBQMxOTQFAzE5NGcQBQMxOTUFAzE5NWcQBQMxOTYFAzE5NmcQBQMxOTcFAzE5N2cQBQMxOTgFAzE5OGcQBQMxOTkFAzE5OWcQBQMyMDAFAzIwMGdkZAI/Dw9kFgIfAAUhamF2YXNjcmlwdDpyZXR1cm4gdmFsaWRhdGVEYXRhKCk7ZAJEDxYCHwRoFgICAQ9kFgICAQ8QZGQWAWZkAkUPD2QWAh8ABTVqYXZhc2NyaXB0OnJldHVybiB2YWxpZGF0ZURhdGEoKSAmJiB2YWxpZGF0ZUZpbHRlcigpO2QCRg8PFgIfBGgWAh8ABTVqYXZhc2NyaXB0OnJldHVybiB2YWxpZGF0ZURhdGEoKSAmJiB2YWxpZGF0ZUZpbHRlcigpO2QCRw8PFgIfBGhkZBgBBR5fX0NvbnRyb2xzUmVxdWlyZVBvc3RCYWNrS2V5X18WJAURSW1hZ2VCdXR0b25TZWFyY2gFEFJhZGlvQnV0dG9uSm9iSWQFEFJhZGlvQnV0dG9uSm9iSWQFElJhZGlvQnV0dG9uSm9iTmFtZQUSUmFkaW9CdXR0b25Kb2JOYW1lBRRSYWRpb0J1dHRvblBvbGljeU51bQUPUmFkaW9CdXR0b25BZGRyBQ9SYWRpb0J1dHRvbkFkZHIFDExpc3RCb3hTdGF0ZQUPY2hrTGlzdFN0YXR1czowBQ9jaGtMaXN0U3RhdHVzOjEFD2Noa0xpc3RTdGF0dXM6MgUPY2hrTGlzdFN0YXR1czozBQ9jaGtMaXN0U3RhdHVzOjQFD2Noa0xpc3RTdGF0dXM6NQUPY2hrTGlzdFN0YXR1czo2BQ9jaGtMaXN0U3RhdHVzOjcFD2Noa0xpc3RTdGF0dXM6OAUPY2hrTGlzdFN0YXR1czo4BQ9DaGVja0JveERlbGV0ZWQFEkltYWdlQnV0dG9uU2VhcmNoMgUSQ2hlY2tPdmVyZHVlQ2xpZW50BRZDaGVja092ZXJkdWVDb250cmFjdG9yBRJJbWFnZUJ1dHRvblNlYXJjaDMFCkxpc3RCb3hQcmQFDkNoZWNrQm94RmFjdG9yBRJJbWFnZUJ1dHRvblNlYXJjaDQFDUxpc3RCb3hDdXN0b20FDExpc3RCb3hDb21JTgUMTGlzdEJveENvbVFDBQxMaXN0Qm94Q29tREUFEkltYWdlQnV0dG9uU2VhcmNoNQULQ2hlY2tCb3hCaWQFEkltYWdlQnV0dG9uU2VhcmNoNgUOQ2hlY2tCb3hJbnZHZW8FC0NoZWNrQm94QWxs2DNFF0bpFRRM0HkM2n55vgf9Bdo=");
      params.put("TopButtonSearch", "Search");
      params.put("TextBoxJobId", "");
      params.put("TextBoxJobName", "");
      params.put("Job", "RadioButtonPolicyNum");
      params.put("TextBoxPolicyNum", "");
      params.put("TextBoxAddress", "");
      params.put("ListBoxState", "");
      params.put("TextBoxCounty", "");
      params.put("TextBoxCity", "");
      params.put("TextBoxZip", "");
      params.put("ListInactiveDB", "");
      params.put("TextBoxSubmissionDateFrom", "");
      params.put("TextBoxSubmissionDateTo", "");
      params.put("TextBoxStartDate", "");
      params.put("TextBoxEndDate", "");
      params.put("TextBoxRepDueStart", "");
      params.put("TextBoxRepDueEnd", "");
      params.put("TextBoxCreatedStart", "04/29/2011");
      params.put("TextBoxCreatedEnd", "");
      params.put("TextBoxWSDStart", "");
      params.put("TextBoxWSDEnd", "");
      params.put("ListBoxPrd", "");
      params.put("RadioButtonListInv", "");
      params.put("RadioButtonListPaid", "");
      params.put("RadioButtonListRepBill", "");
      params.put("RadioButtonListSortNum", "");
      params.put("DropDownListSyncStatus", "All");
      params.put("RadioButtonListPrinted", "-1");
      params.put("DropdownJobViews", "6");
      params.put("DropDownSortBy", "18");
      params.put("RadioListSortOrder", "ASC");
      params.put("DropDownRecordsDisplayed", "0");
      params.put("TextFilterName", "");
      params.put("TextFilterDescription", "");
      return params;   
   }
   
   Date getDate(String date)
   {
      if (date != null && date.trim().length() > 0)
      {
         try
         {
            Date retDate = SHORT_FORMAT.parse(date);
            return (System.currentTimeMillis() - retDate.getTime() > TWO_YEARS) ? null : retDate;
         }
         catch (ParseException e)
         {
         }
      }
      return null;
   }
   
   class ValueScraper extends HTMLEditorKit.ParserCallback
   {
      private Stack<String> tags = new Stack<String>();
      private Map<String, String> valueMap = new HashMap<String, String>();
      private String currentKey = null;
      
      Map<String, String> getValueMap()
      {
         return valueMap;
      }
      
      public void handleText(char[] data, int pos)
      {
         String currentValue = new String(data).trim();
         if (!tags.empty())
         {
            String currentTag = tags.peek();
            if (currentTag.equals("c"))
            {
               currentKey = currentValue;
            }
            else if (currentTag.equals("v") || currentTag.equals("span"))
            {
               valueMap.put(currentKey, currentValue);
            }
            else
            {
               valueMap.put(currentTag, currentValue);
            }
         }
      }

      @Override
      public void handleSimpleTag(Tag t, MutableAttributeSet a, int pos)
      {
         String tag = t.toString();
         if (tags.empty())
         {
            if ("xml".equals(tag))
            {
               // Start parsing at the "xml" tag
               tags.push(tag);
            }
         }
         else
         {
            if (tag.equals(tags.peek()))
            {
               // We shouldn't have a parent and a child with the same tag name
               tags.pop();
            }
            else
            {
               tags.push(tag);
            }
         }
      }

      @Override
      public void handleStartTag(Tag t, MutableAttributeSet a, int pos)
      {
         if (!tags.empty())
         {
            handleSimpleTag(t, a, pos);
         }
         else if ("span".equals(t.toString()))
         {
            if (a.containsAttribute(Attribute.ID, "_ctl0_Main_JobHeaderIN1_LabelRepDueDt"))
            {
               tags.push(t.toString());
               currentKey = "dueDate";
            }
         }
      }

      @Override
      public void handleEndTag(Tag t, int pos)
      {
         if (!tags.empty())
         {
            handleSimpleTag(t, null, pos);
         }
      }
   };
}